In [3]:
import pandas as pd

In [4]:
# importare dataset
df = pd.read_csv("Student_Mental_Stress_and_Coping_Mechanisms.csv")

In [5]:
df.head()

,Student ID,Age,Gender,Academic Performance (GPA),Study Hours Per Week,Social Media Usage (Hours per day),Sleep Duration (Hours per night),Physical Exercise (Hours per week),Family Support,Financial Stress,Peer Pressure,Relationship Stress,Mental Stress Level,Counseling Attendance,Diet Quality,Stress Coping Mechanisms,Cognitive Distortions,Family Mental Health History,Medical Condition,Substance Use
0,802-17-3671,22,Female,2,9,2,12,2,1,1,3,5,9,No,1,Walking or Nature Walks,4,No,Yes,1
1,871-12-8572,25,Female,0,28,0,6,0,1,1,1,2,9,Yes,3,Meditation,2,Yes,No,1
2,495-13-2672,24,Female,0,45,3,12,10,3,3,1,4,9,Yes,5,Reading,1,Yes,Yes,3
3,365-77-2496,20,Male,2,8,7,7,4,1,3,2,5,1,No,1,Social Media Engagement,2,Yes,No,4
4,664-76-5622,28,Male,0,14,6,8,1,2,4,4,2,7,Yes,1,Exercise,1,Yes,No,3

In [6]:
df.isnull()

,Student ID,Age,Gender,Academic Performance (GPA),Study Hours Per Week,Social Media Usage (Hours per day),Sleep Duration (Hours per night),Physical Exercise (Hours per week),Family Support,Financial Stress,Peer Pressure,Relationship Stress,Mental Stress Level,Counseling Attendance,Diet Quality,Stress Coping Mechanisms,Cognitive Distortions,Family Mental Health History,Medical Condition,Substance Use
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
755,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
756,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
757,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
758,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
759,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [7]:
df.isnull().sum()

Student ID                            0
Age                                   0
Gender                                0
Academic Performance (GPA)            0
Study Hours Per Week                  0
Social Media Usage (Hours per day)    0
Sleep Duration (Hours per night)      0
Physical Exercise (Hours per week)    0
Family Support                        0
Financial Stress                      0
Peer Pressure                         0
Relationship Stress                   0
Mental Stress Level                   0
Counseling Attendance                 0
Diet Quality                          0
Stress Coping Mechanisms              0
Cognitive Distortions                 0
Family Mental Health History          0
Medical Condition                     0
Substance Use                         0
dtype: int64

In [8]:
df["Gender"].unique()

array(['Female', 'Male', 'Agender', 'Bigender', 'Genderfluid',
       'Polygender', 'Non-binary', 'Genderqueer'], dtype=object)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 760 entries, 0 to 759
Data columns (total 20 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Student ID                          760 non-null    object
 1   Age                                 760 non-null    int64
 2   Gender                              760 non-null    object
 3   Academic Performance (GPA)          760 non-null    int64
 4   Study Hours Per Week                760 non-null    int64
 5   Social Media Usage (Hours per day)  760 non-null    int64
 6   Sleep Duration (Hours per night)    760 non-null    int64
 7   Physical Exercise (Hours per week)  760 non-null    int64
 8   Family Support                      760 non-null    int64
 9   Financial Stress                    760 non-null    int64
 10  Peer Pressure                       760 non-null    int64
 11  Relationship Stress                 760 non-null    int64
 12  Mental Stress Level                 760 non-null    int64
 13  Counseling Attendance               760 non-null    object
 14  Diet Quality                        760 non-null    int64
 15  Stress Coping Mechanisms            760 non-null    object
 16  Cognitive Distortions               760 non-null    int64
 17  Family Mental Health History        760 non-null    object
 18  Medical Condition                   760 non-null    object
 19  Substance Use                       760 non-null    int64
dtypes: int64(14), object(6)
memory usage: 118.9+ KB

In [10]:
df["Family Support  "].unique()

array([1, 3, 2, 5, 4], dtype=int64)

In [11]:
df.describe()

,Age,Academic Performance (GPA),Study Hours Per Week,Social Media Usage (Hours per day),Sleep Duration (Hours per night),Physical Exercise (Hours per week),Family Support,Financial Stress,Peer Pressure,Relationship Stress,Mental Stress Level,Diet Quality,Cognitive Distortions,Substance Use
count,760.000000,760.000000,760.000000,760.000000,760.000000,760.000000,760.000000,760.000000,760.000000,760.000000,760.000000,760.000000,760.000000,760.000000
mean,23.919737,1.996053,29.130263,4.234211,8.093421,4.934211,2.972368,3.021053,2.982895,2.963158,5.363158,3.042105,3.007895,2.996053
std,3.819392,1.416535,18.104662,2.565174,2.596838,3.082679,1.413477,1.452662,1.391096,1.369231,2.902856,1.453111,1.432703,1.385502
min,18.000000,0.000000,0.000000,0.000000,4.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,21.000000,1.000000,13.000000,2.000000,6.000000,2.000000,2.000000,2.000000,2.000000,2.000000,3.000000,2.000000,2.000000,2.000000
50%,24.000000,2.000000,29.000000,4.000000,8.000000,5.000000,3.000000,3.000000,3.000000,3.000000,5.000000,3.000000,3.000000,3.000000
75%,27.000000,3.000000,45.000000,7.000000,10.000000,8.000000,4.000000,4.000000,4.000000,4.000000,8.000000,4.000000,4.000000,4.000000
max,30.000000,4.000000,60.000000,8.000000,12.000000,10.000000,5.000000,5.000000,5.000000,5.000000,10.000000,5.000000,5.000000,5.000000

In [13]:
df.to_csv('Student_mental_stress.csv', index=False)